config/routes.rb
Rails.application.routes.draw do

  root 'users#index' 
  post 'users/create'   => 'users#create',   as: 'create'
  post 'users/login'    => 'users#login',    as: 'login'
  get 'users/edit'      => 'users#edit',     as: 'edit'
  patch 'users/update'  => 'users#update',   as: 'update'
  delete 'users/logout' => 'users#destroy',  as: 'logout'

  resources :songs

  resources :playlists, only: [:create, :show]

end
 

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
	
	has_many :playlists
	has_many :users, through: :playlists, source: :user

	validates :artist, :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  
  has_many :playlist, dependent: :destroy
  has_many :songs, through: :playlists, source: :song
  

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name, :last_name, :password, :password_confirmation, presence: true
  validates :email,
   uniqueness: { case_sensitive: false }, 
   presence: true,
   format: {with: email_regex}
   

  before_save :setcase

  def setcase
  	self.first_name.downcase!
  	self.last_name.downcase!
  	self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	def index
	end

	def current_user
    	User.find(session[:user_id]) if session[:user_id]
  	end


  helper_method :current_user
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

	def create
		@playlist = Playlist.create(playlist_params)

		if @playlist.valid?
			return redirect_to songs_path
		end

		flash[:errors] = @playlist.errors.full_message

		return redirect_to :back

	end

	def show
		
	end

	private
		def playlist_params
			params.require(:playlist).permit(:song_id).merge(user_id: session[:user_id])
		end
end
	

app/controllers/songs_controller.rb
class SongsController < ApplicationController

	def index
		@songs = Song.all
		p @songs

	end

	def create
		@song = Song.create(song_params)

		if @song.valid?
			p @song
			return redirect_to songs_path

		else
			flash[:errors] = @song.errors.full_messages

			return redirect_to :back
		end
	end 

	def show
		@song = Song.find(params[:id])
	end


	private
		def song_params
			params.require(:song).permit(:artist, :name).merge(user_id: session[:user_id])
		end
	end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = User.all
	end

	def create
		@user = User.create(user_params)

		if @user.valid?
			session[:user_id] = @user.id
			return redirect_to songs_path
		elsif 
			flash[:errors] = @user.errors.full_messages
			return redirect_to :back		
		end
	end

	def login
		@user = User.find_by(email: params[:email])

		if @user
			if @user.try(:authenticate, params[:password])
				session[:user_id] = @user.id

				return redirect_to songs_path
			end
			flash[:errors] = ['Password is incorrect']
		else 
			flash[:errors] = ['Email is invalid']

		end
		return redirect_to :back
	end

	def show
		@user = User.find(params[:id])
	end


	def destroy
  		reset_session

  		return redirect_to root_path
  	end

	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Ruby Belt</title>
		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>
	</head>
	<body>

		<% if current_user %>
				  <form action="<%= logout_path %>" method="post">
				    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
				    <input type="hidden" name="_method" value="delete">
				    <input type="submit" value="Log Out">
				  </form>
				<% end %> 
		<%= yield %>

	</body>
</html>

app/views/playlists/show.html.erb
<h2><%= @playlist %>'s Playlist</h2>
<table>
	<tr>
		<td>Artist</td>
		<td>|</td>
		<td>Title</td>
		<td>|</td>
		<td>Times Added</td>
		<td>|</td>
	</tr>
	
	<tr>
		<td><%=  %></td>
		<td>|</td>
		<td><%=%></td>
		<td>|</td>
		<td><%= %></td>
	</tr>
	
</table>

app/views/songs/index.html.erb
<h1>Hello, <%= current_user.first_name %></h1>

<h4>All the songs in our hub:</h4>
<table>
	<tr>
		<td>Artist</td>
		<td>|</td>
		<td>Name</td>
		<td>|</td>
		<td>No. of times song has been added</td>
		<td>|</td>
		<td>Add to Playlist</td>
	</tr>
	<% @songs.each do |song| %>
	
	<tr>
		<td><%= song.artist %></td>
		<td>|</td>
		<td><a href="<%= song_path song.id %>"><%= song.name %></a></td>
		<td>|</td>
		<td><%= song.playlists.count %></td>
		<td>
			<form action=" <%= playlists_path %>" method="post">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
				<input type="hidden" name="playlist[song_id]" value="<%= song.id %>">
				<input type="submit" value="Add">
			</form>
	</tr>
	<% end %>
	
</table>

<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<p><%= error %></p>
	<% end %>
<% end %>
<h4>Add a Song:</h4>
<form action="<%= songs_path %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<label>Title:</label>
	<input type="text" name="song[name]">

	<label>Artist:</label>
	<input type="text" name="song[artist]">

	<input type="submit" name="submit" value="Add Song">
</form>

app/views/songs/show.html.erb
<a href="<%= songs_path %>">Dashboard</a>

<h1>others who added <%= @song.name %> - <%= @song.artist %></h1>

<table>
	<tr>
		<td>Name</td>
		<td>|</td>
		<td>Times Added</td>
		<td>|</td>
	</tr>

	
	<tr>
		<td><a href=" <%= playlist_path %>"><%= @song.users.first! %></a></td>
		<td>|</td>
		<td><%= @song.playlists.count %></td>
	</tr>
	
</table>

app/views/users/index.html.erb
<h1> Welcome</h1>
<h3>Please Login or Register Below</h3>

<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<p><%= error %></p>
	<% end %>
<% end %>

<div id=register>
	<h3>Register</h3>
	<form action="<%= create_path %>" method="post">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

		<label>First Name:</label>
		<input type="text" name="user[first_name]"><br>

		<label>Last Name:</label><input type="text" name="user[last_name]"><br>

		<label>Email:</label><input type="text" name="user[email]"><br>

		<label>Password:</label><input type="password" name="user[password]"><br>

		<label>Password Confirmation:</label><input type="password" name="user[password_confirmation]"><br>	
		<input type="submit" name="submit" value="Register">
	</form>
</div>

<div id=login>
	<h3>Login</h3>
	<form action="<%= login_path %>" method="post">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		
		<label>Email:</label><input type="text" name="email"><br>

		<label>Password:</label><input type="password" name="password"><br>
		<input type="submit" name="submit" value="Login">
	</form>